create model, repository, service
OleksandrSaven/book-store pull request #1
Opened 2023-09-03 15:44 UTC by OleksandrSaven

2023-09-04 13:04 UTC, ArtemReizer approved these changes
Looks good) GJ!

2023-09-06 07:09 UTC, Visqe approved these changes
LGTM

2023-09-06 14:26 UTC, vovasalyha requested changes
GJ. Let's improve few things.

2023-09-06 14:26 UTC, vovasalyha commented on pom.xml
> +            <artifactId>jakarta.persistence-api</artifactId>
This dependency is added transitively by data-jpa starter

2023-09-06 14:26 UTC, vovasalyha commented on pom.xml
> +            <version>1.18.24</version>
Lombok version is present in parent pom

2023-09-06 14:26 UTC, vovasalyha commented on pom.xml
> +            <version>3.1.0</version>
This version also present in parent pom

2023-09-06 14:26 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/OnlineBookStoreApplication.java
> +        return new CommandLineRunner() {
Better use lambda.

2023-09-06 14:26 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/model/Book.java
> +@Entity
Add `Table` annotation too.

2023-09-06 14:26 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +            Query<Book> getAllBooksQuery = session.createQuery("from Book ", Book.class);
```suggestion
            Query<Book> getAllBooksQuery = session.createQuery("FROM Book ", Book.class);

```

2023-09-06 14:26 UTC, vovasalyha commented on src/main/java/com/app/onlinebookstore/service/impl/BookServiceImpl.java
> +    public BookServiceImpl(BookRepository bookRepository) {
You can use lombok annotation to generate constructor

2023-09-06 14:26 UTC, vovasalyha commented on src/main/resources/application.properties
> +spring.datasource.password=gjujlf123$_0
I hope you are not using this password for your real account :)

2023-09-08 06:27 UTC, boroda4436 approved these changes

2023-09-08 11:46 UTC, merged