Add readme file
OleksandrSaven/book-store pull request #11
Opened 2023-10-25 07:28 UTC by OleksandrSaven

2023-10-25 15:42 UTC, vovasalyha requested changes
GJ, but see a couple of comments. Also, it will be great if you add some interactivity to your README (some media, badges, hyperlinks etc.)

2023-10-25 15:42 UTC, vovasalyha commented on README.md
> +Ensure you have Java Development Kit (JDK) installed on your system.
So, If I have JDK 8, I can build your project?

2023-10-25 15:42 UTC, vovasalyha commented on README.md
> +Check the project's configuration files (usually in the src/main/resources directory) to configure your database connection settings. Ensure you have a MySQL database set up and that you provide the
Provide an option to run your app without manually installing MySQL and configuring a database. Provide a guide how to do all of that using Docker and docker-compose file.

2023-10-26 12:41 UTC, andrii-hoienko requested changes
GJ! Let`s improve your solution

2023-10-26 12:41 UTC, andrii-hoienko commented on README.md
> +6. **Note**: Some requests may require authentication. Ensure you are logged in and have the necessary permissions.
Add something about contribution

2023-10-26 12:41 UTC, andrii-hoienko commented on README.md
> +## How to use
Mention the specific functionalities of your controllers.

2023-10-27 12:18 UTC, andrii-hoienko requested changes
Minor comment left

2023-10-27 12:18 UTC, andrii-hoienko commented on README.md
> +   Thank you for your interest in contributing to online-book-store! We appreciate your help in making the project better for everyone.
Please avoid using 'We'. 'We' means that you worked on the project with someone else

2023-10-27 12:35 UTC, andrii-hoienko approved these changes
Nice

2023-10-27 12:35 UTC, andrii-hoienko commented on README.md
> +We have provided a Postman collection that you can use to test the API endpoints easily.
Please avoid 'We' in all your statements)

2023-10-27 12:39 UTC, merged