add user enity,role implement security
OleksandrSaven/book-store pull request #6
Opened 2023-09-13 18:22 UTC by OleksandrSaven

2023-09-14 08:37 UTC, Denis-Balako requested changes
Good solution! Let's improve it!

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto request) {
add @ Valid  annotation to request dto

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/controller/AuthenticationController.java
> +        return authenticationService.authenticate(request);
```suggestion
            @RequestBody @Valid UserRegistrationRequestDto requestDto)
            throws RegistrationException {
        return userService.register(requestDto);
    }

    @PostMapping("/login")
    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
        return authenticationService.authenticate(requestDto);

```

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/controller/BookController.java
>          return bookService.updateById(id, bookRequestDto);
```suggestion
    public BookDto update(@PathVariable Long id, @Valid
                              @RequestBody CreateBookRequestDto bookRequestDto) {
        return bookService.update(id, bookRequestDto);

```

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/dto/UserLoginRequestDto.java
> +        String password) {
```suggestion
        @NotBlank @Email String email,
        @NotBlank @Size(min = 6) String password) {

```

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/validation/FieldMatch.java
> +    String second();
Rename this variables to more understanding, such as "field":"fieldMatch"

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/dto/UserRegistrationRequestDto.java
> +    @Size(min = 4, max = 50)
use @ Length for String type

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/exaption/CustomGlobalExceptionHandler.java
Add Exception handlers for other exceptions, such as RegistrationException

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/model/User.java
> +            inverseJoinColumns = @JoinColumn(name = "role_id"))
```suggestion
            inverseJoinColumns = @JoinColumn(name = "role_id"))
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
```

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/model/User.java
> +        return authorities;
Optional: u can use Stream API for more elegant implementation 🪄

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/repository/UserRepository.java
> +    @Query("SELECT u FROM User u LEFT JOIN FETCH u.roles WHERE u.email = :email")
```suggestion
    @Query("FROM User u LEFT JOIN FETCH u.roles WHERE u.email = :email")
```

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/security/AuthenticationService.java
> +
Redundant empty line

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
Magic numbers and strings

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/security/JwtUtil.java
> +            throw new JwtException("Expired or invalid JWT token");
```suggestion
            throw new JwtException("Expired or invalid JWT token", e);
```

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/service/impl/UserServiceImpl.java
> +        User user = new User();
Optional: implement toModel method in mapper, for more readable code (all stuff such as password encode do in in service)

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/service/impl/UserServiceImpl.java
> +                new NoSuchElementException("Can't find such role"));
Write more detailed message. Which role I can't find?

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/java/com/app/onlinebookstore/service/impl/UserServiceImpl.java
> +        user.setRoles(roles);
```suggestion
        Role defaultRole = roleRepository.findByRoleName(
                RoleName.ROLE_USER).orElseThrow(() ->
                new NoSuchElementException("Can't find such role"));
        roles.add(Set.of(defaultRole));
        user.setRoles(roles);
```

2023-09-14 08:37 UTC, Denis-Balako commented on src/main/resources/db/changelog/changes/05-insert-user-and-admin-table.yaml
> +                  value: 13 st Lincoln ave.
add empty line in the end of the file

2023-09-14 15:27 UTC, OleksandrSaven commented on src/main/java/com/app/onlinebookstore/dto/UserRegistrationRequestDto.java
> +    @Size(min = 4, max = 50)
@Langth  - is annotation from hibernate, @Size from - Spring.  In my opinion better use @Size

2023-09-14 16:05 UTC, vovasalyha requested changes
GJ, but add constraints for a linking table

2023-09-14 16:05 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/04-create-user-roles-table.yaml
> +                  name: user_id
Add constraints to this table. Primary key (user_id, role_id) and foreign keys for both columns

2023-09-15 12:00 UTC, andrii-hoienko requested changes
Nice, but some improvements required

2023-09-15 12:00 UTC, andrii-hoienko commented on pom.xml
> +            <version>0.11.5</version>
It is better to use version property for all version tags

2023-09-15 12:00 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new RuntimeException("Can't find user by email" + username));
can`t find by email or by username?

2023-09-15 12:00 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/security/JwtAuthenticationFilter.java
> +    private static final int START_TOKEN_INDEX = 7;
It is possible to user BEARER_TOKEN.lenght instead of creating constant

2023-09-15 12:44 UTC, andrii-hoienko approved these changes
Nice

2023-09-22 07:55 UTC, merged