Implement order entity
OleksandrSaven/book-store pull request #9
Opened 2023-09-26 05:17 UTC by OleksandrSaven

2023-09-26 14:58 UTC, IhorKalaur requested changes
Good Job, but need add roles for user

2023-09-26 14:58 UTC, IhorKalaur commented on src/main/java/com/app/onlinebookstore/controller/OrderController.java
> +    public OrderDto createOrder(@RequestBody @Valid CreateOrderRequestDto requestDto,
This  method must be available only for users with role "User"

2023-09-26 14:58 UTC, IhorKalaur commented on src/main/java/com/app/onlinebookstore/controller/OrderController.java
> +    public List<OrderDto> findAllOrder(Pageable pageable) {
All find method just for users

2023-09-27 12:36 UTC, andrii-hoienko requested changes
GJ! Let`s improve your solution

2023-09-27 12:36 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/model/Order.java
> +    @ManyToOne
Please make toOne relations lazy

2023-09-27 12:36 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/service/impl/CartItemServiceImpl.java
> +        Long userId = userService.getAuthenticatedUser().getId();
This method can be significantly simplified. I suggest to make changes in cartItem repository to delete cartItems which belongs to the user. This approach will reduce number of database requests to one and improve code readability

2023-09-27 12:36 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/service/impl/OrderServiceImpl.java
> +        for (Order order : orders) {
Please don`t make n+1 requests by yourself. I suggest to retrieve all order items instantly if needed, by one db request

2023-09-27 12:36 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/service/impl/OrderServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository
For retrieving shopping cart and handling notFoundEx should be responsible shoppingCartService

2023-09-27 12:36 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/service/impl/OrderServiceImpl.java
> +        Order order = new Order();
To improve readability it will be better to extract order creation logic to separate method

2023-09-27 12:36 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/service/impl/OrderServiceImpl.java
> +                .map(orderItemRepository::save)
It is possible to use cascades to save order and orderItems together

2023-09-27 12:36 UTC, andrii-hoienko commented on src/main/java/com/app/onlinebookstore/service/impl/OrderServiceImpl.java
> +        Set<OrderItem> orderItems = orderRepository.getOrderByUserId(user.getId()).stream()
Please retrieve already assigned to user(order) orderItems from db, not by retrieving all and filtering. Please do same in other methods

2023-09-29 14:27 UTC, vovasalyha approved these changes

2023-09-29 14:51 UTC, merged